//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UEditorDemo.UploadFile {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SizeModle", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SizeModle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int widthField;
        
        private int heightField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int width {
            get {
                return this.widthField;
            }
            set {
                if ((this.widthField.Equals(value) != true)) {
                    this.widthField = value;
                    this.RaisePropertyChanged("width");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int height {
            get {
                return this.heightField;
            }
            set {
                if ((this.heightField.Equals(value) != true)) {
                    this.heightField = value;
                    this.RaisePropertyChanged("height");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UploadFile.UploadFileSoap")]
    public interface UploadFileSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 data 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpLoadFiles", ReplyAction="*")]
        UEditorDemo.UploadFile.UpLoadFilesResponse UpLoadFiles(UEditorDemo.UploadFile.UpLoadFilesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpLoadFiles", ReplyAction="*")]
        System.Threading.Tasks.Task<UEditorDemo.UploadFile.UpLoadFilesResponse> UpLoadFilesAsync(UEditorDemo.UploadFile.UpLoadFilesRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 data 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpLoadAndBuildThum", ReplyAction="*")]
        UEditorDemo.UploadFile.UpLoadAndBuildThumResponse UpLoadAndBuildThum(UEditorDemo.UploadFile.UpLoadAndBuildThumRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpLoadAndBuildThum", ReplyAction="*")]
        System.Threading.Tasks.Task<UEditorDemo.UploadFile.UpLoadAndBuildThumResponse> UpLoadAndBuildThumAsync(UEditorDemo.UploadFile.UpLoadAndBuildThumRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 data 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpLoadImages", ReplyAction="*")]
        UEditorDemo.UploadFile.UpLoadImagesResponse UpLoadImages(UEditorDemo.UploadFile.UpLoadImagesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpLoadImages", ReplyAction="*")]
        System.Threading.Tasks.Task<UEditorDemo.UploadFile.UpLoadImagesResponse> UpLoadImagesAsync(UEditorDemo.UploadFile.UpLoadImagesRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 data 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpLoadAndBuildManyThum", ReplyAction="*")]
        UEditorDemo.UploadFile.UpLoadAndBuildManyThumResponse UpLoadAndBuildManyThum(UEditorDemo.UploadFile.UpLoadAndBuildManyThumRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpLoadAndBuildManyThum", ReplyAction="*")]
        System.Threading.Tasks.Task<UEditorDemo.UploadFile.UpLoadAndBuildManyThumResponse> UpLoadAndBuildManyThumAsync(UEditorDemo.UploadFile.UpLoadAndBuildManyThumRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 filePath 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpLoadandBuildSub", ReplyAction="*")]
        UEditorDemo.UploadFile.UpLoadandBuildSubResponse UpLoadandBuildSub(UEditorDemo.UploadFile.UpLoadandBuildSubRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpLoadandBuildSub", ReplyAction="*")]
        System.Threading.Tasks.Task<UEditorDemo.UploadFile.UpLoadandBuildSubResponse> UpLoadandBuildSubAsync(UEditorDemo.UploadFile.UpLoadandBuildSubRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 filepath 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        UEditorDemo.UploadFile.DeleteResponse Delete(UEditorDemo.UploadFile.DeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<UEditorDemo.UploadFile.DeleteResponse> DeleteAsync(UEditorDemo.UploadFile.DeleteRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 filepaths 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteMore", ReplyAction="*")]
        UEditorDemo.UploadFile.DeleteMoreResponse DeleteMore(UEditorDemo.UploadFile.DeleteMoreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteMore", ReplyAction="*")]
        System.Threading.Tasks.Task<UEditorDemo.UploadFile.DeleteMoreResponse> DeleteMoreAsync(UEditorDemo.UploadFile.DeleteMoreRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 filepath 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFileBytes", ReplyAction="*")]
        UEditorDemo.UploadFile.GetFileBytesResponse GetFileBytes(UEditorDemo.UploadFile.GetFileBytesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFileBytes", ReplyAction="*")]
        System.Threading.Tasks.Task<UEditorDemo.UploadFile.GetFileBytesResponse> GetFileBytesAsync(UEditorDemo.UploadFile.GetFileBytesRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 path 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowImage", ReplyAction="*")]
        UEditorDemo.UploadFile.ShowImageResponse ShowImage(UEditorDemo.UploadFile.ShowImageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowImage", ReplyAction="*")]
        System.Threading.Tasks.Task<UEditorDemo.UploadFile.ShowImageResponse> ShowImageAsync(UEditorDemo.UploadFile.ShowImageRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 sUrl 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DownLoadFile", ReplyAction="*")]
        UEditorDemo.UploadFile.DownLoadFileResponse DownLoadFile(UEditorDemo.UploadFile.DownLoadFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DownLoadFile", ReplyAction="*")]
        System.Threading.Tasks.Task<UEditorDemo.UploadFile.DownLoadFileResponse> DownLoadFileAsync(UEditorDemo.UploadFile.DownLoadFileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpLoadFilesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpLoadFiles", Namespace="http://tempuri.org/", Order=0)]
        public UEditorDemo.UploadFile.UpLoadFilesRequestBody Body;
        
        public UpLoadFilesRequest() {
        }
        
        public UpLoadFilesRequest(UEditorDemo.UploadFile.UpLoadFilesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpLoadFilesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] data;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string filename;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sDirectoryName;
        
        public UpLoadFilesRequestBody() {
        }
        
        public UpLoadFilesRequestBody(byte[] data, string filename, string sDirectoryName) {
            this.data = data;
            this.filename = filename;
            this.sDirectoryName = sDirectoryName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpLoadFilesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpLoadFilesResponse", Namespace="http://tempuri.org/", Order=0)]
        public UEditorDemo.UploadFile.UpLoadFilesResponseBody Body;
        
        public UpLoadFilesResponse() {
        }
        
        public UpLoadFilesResponse(UEditorDemo.UploadFile.UpLoadFilesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpLoadFilesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpLoadFilesResult;
        
        public UpLoadFilesResponseBody() {
        }
        
        public UpLoadFilesResponseBody(string UpLoadFilesResult) {
            this.UpLoadFilesResult = UpLoadFilesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpLoadAndBuildThumRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpLoadAndBuildThum", Namespace="http://tempuri.org/", Order=0)]
        public UEditorDemo.UploadFile.UpLoadAndBuildThumRequestBody Body;
        
        public UpLoadAndBuildThumRequest() {
        }
        
        public UpLoadAndBuildThumRequest(UEditorDemo.UploadFile.UpLoadAndBuildThumRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpLoadAndBuildThumRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] data;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string filename;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sDirectoryName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int iWidth;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int iHeight;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string sMode;
        
        public UpLoadAndBuildThumRequestBody() {
        }
        
        public UpLoadAndBuildThumRequestBody(byte[] data, string filename, string sDirectoryName, int iWidth, int iHeight, string sMode) {
            this.data = data;
            this.filename = filename;
            this.sDirectoryName = sDirectoryName;
            this.iWidth = iWidth;
            this.iHeight = iHeight;
            this.sMode = sMode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpLoadAndBuildThumResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpLoadAndBuildThumResponse", Namespace="http://tempuri.org/", Order=0)]
        public UEditorDemo.UploadFile.UpLoadAndBuildThumResponseBody Body;
        
        public UpLoadAndBuildThumResponse() {
        }
        
        public UpLoadAndBuildThumResponse(UEditorDemo.UploadFile.UpLoadAndBuildThumResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpLoadAndBuildThumResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpLoadAndBuildThumResult;
        
        public UpLoadAndBuildThumResponseBody() {
        }
        
        public UpLoadAndBuildThumResponseBody(string UpLoadAndBuildThumResult) {
            this.UpLoadAndBuildThumResult = UpLoadAndBuildThumResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpLoadImagesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpLoadImages", Namespace="http://tempuri.org/", Order=0)]
        public UEditorDemo.UploadFile.UpLoadImagesRequestBody Body;
        
        public UpLoadImagesRequest() {
        }
        
        public UpLoadImagesRequest(UEditorDemo.UploadFile.UpLoadImagesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpLoadImagesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] data;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string filename;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sDirectoryName;
        
        public UpLoadImagesRequestBody() {
        }
        
        public UpLoadImagesRequestBody(byte[] data, string filename, string sDirectoryName) {
            this.data = data;
            this.filename = filename;
            this.sDirectoryName = sDirectoryName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpLoadImagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpLoadImagesResponse", Namespace="http://tempuri.org/", Order=0)]
        public UEditorDemo.UploadFile.UpLoadImagesResponseBody Body;
        
        public UpLoadImagesResponse() {
        }
        
        public UpLoadImagesResponse(UEditorDemo.UploadFile.UpLoadImagesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpLoadImagesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpLoadImagesResult;
        
        public UpLoadImagesResponseBody() {
        }
        
        public UpLoadImagesResponseBody(string UpLoadImagesResult) {
            this.UpLoadImagesResult = UpLoadImagesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpLoadAndBuildManyThumRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpLoadAndBuildManyThum", Namespace="http://tempuri.org/", Order=0)]
        public UEditorDemo.UploadFile.UpLoadAndBuildManyThumRequestBody Body;
        
        public UpLoadAndBuildManyThumRequest() {
        }
        
        public UpLoadAndBuildManyThumRequest(UEditorDemo.UploadFile.UpLoadAndBuildManyThumRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpLoadAndBuildManyThumRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] data;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string filename;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sDirectoryName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public UEditorDemo.UploadFile.SizeModle[] widthHeight;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sMode;
        
        public UpLoadAndBuildManyThumRequestBody() {
        }
        
        public UpLoadAndBuildManyThumRequestBody(byte[] data, string filename, string sDirectoryName, UEditorDemo.UploadFile.SizeModle[] widthHeight, string sMode) {
            this.data = data;
            this.filename = filename;
            this.sDirectoryName = sDirectoryName;
            this.widthHeight = widthHeight;
            this.sMode = sMode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpLoadAndBuildManyThumResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpLoadAndBuildManyThumResponse", Namespace="http://tempuri.org/", Order=0)]
        public UEditorDemo.UploadFile.UpLoadAndBuildManyThumResponseBody Body;
        
        public UpLoadAndBuildManyThumResponse() {
        }
        
        public UpLoadAndBuildManyThumResponse(UEditorDemo.UploadFile.UpLoadAndBuildManyThumResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpLoadAndBuildManyThumResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpLoadAndBuildManyThumResult;
        
        public UpLoadAndBuildManyThumResponseBody() {
        }
        
        public UpLoadAndBuildManyThumResponseBody(string UpLoadAndBuildManyThumResult) {
            this.UpLoadAndBuildManyThumResult = UpLoadAndBuildManyThumResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpLoadandBuildSubRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpLoadandBuildSub", Namespace="http://tempuri.org/", Order=0)]
        public UEditorDemo.UploadFile.UpLoadandBuildSubRequestBody Body;
        
        public UpLoadandBuildSubRequest() {
        }
        
        public UpLoadandBuildSubRequest(UEditorDemo.UploadFile.UpLoadandBuildSubRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpLoadandBuildSubRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string filePath;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int iWidth;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int iHeight;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sMode;
        
        public UpLoadandBuildSubRequestBody() {
        }
        
        public UpLoadandBuildSubRequestBody(string filePath, int iWidth, int iHeight, string sMode) {
            this.filePath = filePath;
            this.iWidth = iWidth;
            this.iHeight = iHeight;
            this.sMode = sMode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpLoadandBuildSubResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpLoadandBuildSubResponse", Namespace="http://tempuri.org/", Order=0)]
        public UEditorDemo.UploadFile.UpLoadandBuildSubResponseBody Body;
        
        public UpLoadandBuildSubResponse() {
        }
        
        public UpLoadandBuildSubResponse(UEditorDemo.UploadFile.UpLoadandBuildSubResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpLoadandBuildSubResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpLoadandBuildSubResult;
        
        public UpLoadandBuildSubResponseBody() {
        }
        
        public UpLoadandBuildSubResponseBody(string UpLoadandBuildSubResult) {
            this.UpLoadandBuildSubResult = UpLoadandBuildSubResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete", Namespace="http://tempuri.org/", Order=0)]
        public UEditorDemo.UploadFile.DeleteRequestBody Body;
        
        public DeleteRequest() {
        }
        
        public DeleteRequest(UEditorDemo.UploadFile.DeleteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string filepath;
        
        public DeleteRequestBody() {
        }
        
        public DeleteRequestBody(string filepath) {
            this.filepath = filepath;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteResponse", Namespace="http://tempuri.org/", Order=0)]
        public UEditorDemo.UploadFile.DeleteResponseBody Body;
        
        public DeleteResponse() {
        }
        
        public DeleteResponse(UEditorDemo.UploadFile.DeleteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int DeleteResult;
        
        public DeleteResponseBody() {
        }
        
        public DeleteResponseBody(int DeleteResult) {
            this.DeleteResult = DeleteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteMoreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteMore", Namespace="http://tempuri.org/", Order=0)]
        public UEditorDemo.UploadFile.DeleteMoreRequestBody Body;
        
        public DeleteMoreRequest() {
        }
        
        public DeleteMoreRequest(UEditorDemo.UploadFile.DeleteMoreRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteMoreRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UEditorDemo.UploadFile.ArrayOfString filepaths;
        
        public DeleteMoreRequestBody() {
        }
        
        public DeleteMoreRequestBody(UEditorDemo.UploadFile.ArrayOfString filepaths) {
            this.filepaths = filepaths;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteMoreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteMoreResponse", Namespace="http://tempuri.org/", Order=0)]
        public UEditorDemo.UploadFile.DeleteMoreResponseBody Body;
        
        public DeleteMoreResponse() {
        }
        
        public DeleteMoreResponse(UEditorDemo.UploadFile.DeleteMoreResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteMoreResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int DeleteMoreResult;
        
        public DeleteMoreResponseBody() {
        }
        
        public DeleteMoreResponseBody(int DeleteMoreResult) {
            this.DeleteMoreResult = DeleteMoreResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileBytesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileBytes", Namespace="http://tempuri.org/", Order=0)]
        public UEditorDemo.UploadFile.GetFileBytesRequestBody Body;
        
        public GetFileBytesRequest() {
        }
        
        public GetFileBytesRequest(UEditorDemo.UploadFile.GetFileBytesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileBytesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string filepath;
        
        public GetFileBytesRequestBody() {
        }
        
        public GetFileBytesRequestBody(string filepath) {
            this.filepath = filepath;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileBytesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileBytesResponse", Namespace="http://tempuri.org/", Order=0)]
        public UEditorDemo.UploadFile.GetFileBytesResponseBody Body;
        
        public GetFileBytesResponse() {
        }
        
        public GetFileBytesResponse(UEditorDemo.UploadFile.GetFileBytesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileBytesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] GetFileBytesResult;
        
        public GetFileBytesResponseBody() {
        }
        
        public GetFileBytesResponseBody(byte[] GetFileBytesResult) {
            this.GetFileBytesResult = GetFileBytesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowImageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowImage", Namespace="http://tempuri.org/", Order=0)]
        public UEditorDemo.UploadFile.ShowImageRequestBody Body;
        
        public ShowImageRequest() {
        }
        
        public ShowImageRequest(UEditorDemo.UploadFile.ShowImageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ShowImageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string path;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int PointX;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int PointY;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int CutWidth;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int CutHeight;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int PicWidth;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int PicHeight;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string FolderName;
        
        public ShowImageRequestBody() {
        }
        
        public ShowImageRequestBody(string path, int PointX, int PointY, int CutWidth, int CutHeight, int PicWidth, int PicHeight, string FolderName) {
            this.path = path;
            this.PointX = PointX;
            this.PointY = PointY;
            this.CutWidth = CutWidth;
            this.CutHeight = CutHeight;
            this.PicWidth = PicWidth;
            this.PicHeight = PicHeight;
            this.FolderName = FolderName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowImageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowImageResponse", Namespace="http://tempuri.org/", Order=0)]
        public UEditorDemo.UploadFile.ShowImageResponseBody Body;
        
        public ShowImageResponse() {
        }
        
        public ShowImageResponse(UEditorDemo.UploadFile.ShowImageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ShowImageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ShowImageResult;
        
        public ShowImageResponseBody() {
        }
        
        public ShowImageResponseBody(string ShowImageResult) {
            this.ShowImageResult = ShowImageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownLoadFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownLoadFile", Namespace="http://tempuri.org/", Order=0)]
        public UEditorDemo.UploadFile.DownLoadFileRequestBody Body;
        
        public DownLoadFileRequest() {
        }
        
        public DownLoadFileRequest(UEditorDemo.UploadFile.DownLoadFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DownLoadFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sUrl;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sDownFold;
        
        public DownLoadFileRequestBody() {
        }
        
        public DownLoadFileRequestBody(string sUrl, string sDownFold) {
            this.sUrl = sUrl;
            this.sDownFold = sDownFold;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownLoadFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownLoadFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public UEditorDemo.UploadFile.DownLoadFileResponseBody Body;
        
        public DownLoadFileResponse() {
        }
        
        public DownLoadFileResponse(UEditorDemo.UploadFile.DownLoadFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DownLoadFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DownLoadFileResult;
        
        public DownLoadFileResponseBody() {
        }
        
        public DownLoadFileResponseBody(string DownLoadFileResult) {
            this.DownLoadFileResult = DownLoadFileResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UploadFileSoapChannel : UEditorDemo.UploadFile.UploadFileSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UploadFileSoapClient : System.ServiceModel.ClientBase<UEditorDemo.UploadFile.UploadFileSoap>, UEditorDemo.UploadFile.UploadFileSoap {
        
        public UploadFileSoapClient() {
        }
        
        public UploadFileSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UploadFileSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UploadFileSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UploadFileSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UEditorDemo.UploadFile.UpLoadFilesResponse UEditorDemo.UploadFile.UploadFileSoap.UpLoadFiles(UEditorDemo.UploadFile.UpLoadFilesRequest request) {
            return base.Channel.UpLoadFiles(request);
        }
        
        public string UpLoadFiles(byte[] data, string filename, string sDirectoryName) {
            UEditorDemo.UploadFile.UpLoadFilesRequest inValue = new UEditorDemo.UploadFile.UpLoadFilesRequest();
            inValue.Body = new UEditorDemo.UploadFile.UpLoadFilesRequestBody();
            inValue.Body.data = data;
            inValue.Body.filename = filename;
            inValue.Body.sDirectoryName = sDirectoryName;
            UEditorDemo.UploadFile.UpLoadFilesResponse retVal = ((UEditorDemo.UploadFile.UploadFileSoap)(this)).UpLoadFiles(inValue);
            return retVal.Body.UpLoadFilesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UEditorDemo.UploadFile.UpLoadFilesResponse> UEditorDemo.UploadFile.UploadFileSoap.UpLoadFilesAsync(UEditorDemo.UploadFile.UpLoadFilesRequest request) {
            return base.Channel.UpLoadFilesAsync(request);
        }
        
        public System.Threading.Tasks.Task<UEditorDemo.UploadFile.UpLoadFilesResponse> UpLoadFilesAsync(byte[] data, string filename, string sDirectoryName) {
            UEditorDemo.UploadFile.UpLoadFilesRequest inValue = new UEditorDemo.UploadFile.UpLoadFilesRequest();
            inValue.Body = new UEditorDemo.UploadFile.UpLoadFilesRequestBody();
            inValue.Body.data = data;
            inValue.Body.filename = filename;
            inValue.Body.sDirectoryName = sDirectoryName;
            return ((UEditorDemo.UploadFile.UploadFileSoap)(this)).UpLoadFilesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UEditorDemo.UploadFile.UpLoadAndBuildThumResponse UEditorDemo.UploadFile.UploadFileSoap.UpLoadAndBuildThum(UEditorDemo.UploadFile.UpLoadAndBuildThumRequest request) {
            return base.Channel.UpLoadAndBuildThum(request);
        }
        
        public string UpLoadAndBuildThum(byte[] data, string filename, string sDirectoryName, int iWidth, int iHeight, string sMode) {
            UEditorDemo.UploadFile.UpLoadAndBuildThumRequest inValue = new UEditorDemo.UploadFile.UpLoadAndBuildThumRequest();
            inValue.Body = new UEditorDemo.UploadFile.UpLoadAndBuildThumRequestBody();
            inValue.Body.data = data;
            inValue.Body.filename = filename;
            inValue.Body.sDirectoryName = sDirectoryName;
            inValue.Body.iWidth = iWidth;
            inValue.Body.iHeight = iHeight;
            inValue.Body.sMode = sMode;
            UEditorDemo.UploadFile.UpLoadAndBuildThumResponse retVal = ((UEditorDemo.UploadFile.UploadFileSoap)(this)).UpLoadAndBuildThum(inValue);
            return retVal.Body.UpLoadAndBuildThumResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UEditorDemo.UploadFile.UpLoadAndBuildThumResponse> UEditorDemo.UploadFile.UploadFileSoap.UpLoadAndBuildThumAsync(UEditorDemo.UploadFile.UpLoadAndBuildThumRequest request) {
            return base.Channel.UpLoadAndBuildThumAsync(request);
        }
        
        public System.Threading.Tasks.Task<UEditorDemo.UploadFile.UpLoadAndBuildThumResponse> UpLoadAndBuildThumAsync(byte[] data, string filename, string sDirectoryName, int iWidth, int iHeight, string sMode) {
            UEditorDemo.UploadFile.UpLoadAndBuildThumRequest inValue = new UEditorDemo.UploadFile.UpLoadAndBuildThumRequest();
            inValue.Body = new UEditorDemo.UploadFile.UpLoadAndBuildThumRequestBody();
            inValue.Body.data = data;
            inValue.Body.filename = filename;
            inValue.Body.sDirectoryName = sDirectoryName;
            inValue.Body.iWidth = iWidth;
            inValue.Body.iHeight = iHeight;
            inValue.Body.sMode = sMode;
            return ((UEditorDemo.UploadFile.UploadFileSoap)(this)).UpLoadAndBuildThumAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UEditorDemo.UploadFile.UpLoadImagesResponse UEditorDemo.UploadFile.UploadFileSoap.UpLoadImages(UEditorDemo.UploadFile.UpLoadImagesRequest request) {
            return base.Channel.UpLoadImages(request);
        }
        
        public string UpLoadImages(byte[] data, string filename, string sDirectoryName) {
            UEditorDemo.UploadFile.UpLoadImagesRequest inValue = new UEditorDemo.UploadFile.UpLoadImagesRequest();
            inValue.Body = new UEditorDemo.UploadFile.UpLoadImagesRequestBody();
            inValue.Body.data = data;
            inValue.Body.filename = filename;
            inValue.Body.sDirectoryName = sDirectoryName;
            UEditorDemo.UploadFile.UpLoadImagesResponse retVal = ((UEditorDemo.UploadFile.UploadFileSoap)(this)).UpLoadImages(inValue);
            return retVal.Body.UpLoadImagesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UEditorDemo.UploadFile.UpLoadImagesResponse> UEditorDemo.UploadFile.UploadFileSoap.UpLoadImagesAsync(UEditorDemo.UploadFile.UpLoadImagesRequest request) {
            return base.Channel.UpLoadImagesAsync(request);
        }
        
        public System.Threading.Tasks.Task<UEditorDemo.UploadFile.UpLoadImagesResponse> UpLoadImagesAsync(byte[] data, string filename, string sDirectoryName) {
            UEditorDemo.UploadFile.UpLoadImagesRequest inValue = new UEditorDemo.UploadFile.UpLoadImagesRequest();
            inValue.Body = new UEditorDemo.UploadFile.UpLoadImagesRequestBody();
            inValue.Body.data = data;
            inValue.Body.filename = filename;
            inValue.Body.sDirectoryName = sDirectoryName;
            return ((UEditorDemo.UploadFile.UploadFileSoap)(this)).UpLoadImagesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UEditorDemo.UploadFile.UpLoadAndBuildManyThumResponse UEditorDemo.UploadFile.UploadFileSoap.UpLoadAndBuildManyThum(UEditorDemo.UploadFile.UpLoadAndBuildManyThumRequest request) {
            return base.Channel.UpLoadAndBuildManyThum(request);
        }
        
        public string UpLoadAndBuildManyThum(byte[] data, string filename, string sDirectoryName, UEditorDemo.UploadFile.SizeModle[] widthHeight, string sMode) {
            UEditorDemo.UploadFile.UpLoadAndBuildManyThumRequest inValue = new UEditorDemo.UploadFile.UpLoadAndBuildManyThumRequest();
            inValue.Body = new UEditorDemo.UploadFile.UpLoadAndBuildManyThumRequestBody();
            inValue.Body.data = data;
            inValue.Body.filename = filename;
            inValue.Body.sDirectoryName = sDirectoryName;
            inValue.Body.widthHeight = widthHeight;
            inValue.Body.sMode = sMode;
            UEditorDemo.UploadFile.UpLoadAndBuildManyThumResponse retVal = ((UEditorDemo.UploadFile.UploadFileSoap)(this)).UpLoadAndBuildManyThum(inValue);
            return retVal.Body.UpLoadAndBuildManyThumResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UEditorDemo.UploadFile.UpLoadAndBuildManyThumResponse> UEditorDemo.UploadFile.UploadFileSoap.UpLoadAndBuildManyThumAsync(UEditorDemo.UploadFile.UpLoadAndBuildManyThumRequest request) {
            return base.Channel.UpLoadAndBuildManyThumAsync(request);
        }
        
        public System.Threading.Tasks.Task<UEditorDemo.UploadFile.UpLoadAndBuildManyThumResponse> UpLoadAndBuildManyThumAsync(byte[] data, string filename, string sDirectoryName, UEditorDemo.UploadFile.SizeModle[] widthHeight, string sMode) {
            UEditorDemo.UploadFile.UpLoadAndBuildManyThumRequest inValue = new UEditorDemo.UploadFile.UpLoadAndBuildManyThumRequest();
            inValue.Body = new UEditorDemo.UploadFile.UpLoadAndBuildManyThumRequestBody();
            inValue.Body.data = data;
            inValue.Body.filename = filename;
            inValue.Body.sDirectoryName = sDirectoryName;
            inValue.Body.widthHeight = widthHeight;
            inValue.Body.sMode = sMode;
            return ((UEditorDemo.UploadFile.UploadFileSoap)(this)).UpLoadAndBuildManyThumAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UEditorDemo.UploadFile.UpLoadandBuildSubResponse UEditorDemo.UploadFile.UploadFileSoap.UpLoadandBuildSub(UEditorDemo.UploadFile.UpLoadandBuildSubRequest request) {
            return base.Channel.UpLoadandBuildSub(request);
        }
        
        public string UpLoadandBuildSub(string filePath, int iWidth, int iHeight, string sMode) {
            UEditorDemo.UploadFile.UpLoadandBuildSubRequest inValue = new UEditorDemo.UploadFile.UpLoadandBuildSubRequest();
            inValue.Body = new UEditorDemo.UploadFile.UpLoadandBuildSubRequestBody();
            inValue.Body.filePath = filePath;
            inValue.Body.iWidth = iWidth;
            inValue.Body.iHeight = iHeight;
            inValue.Body.sMode = sMode;
            UEditorDemo.UploadFile.UpLoadandBuildSubResponse retVal = ((UEditorDemo.UploadFile.UploadFileSoap)(this)).UpLoadandBuildSub(inValue);
            return retVal.Body.UpLoadandBuildSubResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UEditorDemo.UploadFile.UpLoadandBuildSubResponse> UEditorDemo.UploadFile.UploadFileSoap.UpLoadandBuildSubAsync(UEditorDemo.UploadFile.UpLoadandBuildSubRequest request) {
            return base.Channel.UpLoadandBuildSubAsync(request);
        }
        
        public System.Threading.Tasks.Task<UEditorDemo.UploadFile.UpLoadandBuildSubResponse> UpLoadandBuildSubAsync(string filePath, int iWidth, int iHeight, string sMode) {
            UEditorDemo.UploadFile.UpLoadandBuildSubRequest inValue = new UEditorDemo.UploadFile.UpLoadandBuildSubRequest();
            inValue.Body = new UEditorDemo.UploadFile.UpLoadandBuildSubRequestBody();
            inValue.Body.filePath = filePath;
            inValue.Body.iWidth = iWidth;
            inValue.Body.iHeight = iHeight;
            inValue.Body.sMode = sMode;
            return ((UEditorDemo.UploadFile.UploadFileSoap)(this)).UpLoadandBuildSubAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UEditorDemo.UploadFile.DeleteResponse UEditorDemo.UploadFile.UploadFileSoap.Delete(UEditorDemo.UploadFile.DeleteRequest request) {
            return base.Channel.Delete(request);
        }
        
        public int Delete(string filepath) {
            UEditorDemo.UploadFile.DeleteRequest inValue = new UEditorDemo.UploadFile.DeleteRequest();
            inValue.Body = new UEditorDemo.UploadFile.DeleteRequestBody();
            inValue.Body.filepath = filepath;
            UEditorDemo.UploadFile.DeleteResponse retVal = ((UEditorDemo.UploadFile.UploadFileSoap)(this)).Delete(inValue);
            return retVal.Body.DeleteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UEditorDemo.UploadFile.DeleteResponse> UEditorDemo.UploadFile.UploadFileSoap.DeleteAsync(UEditorDemo.UploadFile.DeleteRequest request) {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<UEditorDemo.UploadFile.DeleteResponse> DeleteAsync(string filepath) {
            UEditorDemo.UploadFile.DeleteRequest inValue = new UEditorDemo.UploadFile.DeleteRequest();
            inValue.Body = new UEditorDemo.UploadFile.DeleteRequestBody();
            inValue.Body.filepath = filepath;
            return ((UEditorDemo.UploadFile.UploadFileSoap)(this)).DeleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UEditorDemo.UploadFile.DeleteMoreResponse UEditorDemo.UploadFile.UploadFileSoap.DeleteMore(UEditorDemo.UploadFile.DeleteMoreRequest request) {
            return base.Channel.DeleteMore(request);
        }
        
        public int DeleteMore(UEditorDemo.UploadFile.ArrayOfString filepaths) {
            UEditorDemo.UploadFile.DeleteMoreRequest inValue = new UEditorDemo.UploadFile.DeleteMoreRequest();
            inValue.Body = new UEditorDemo.UploadFile.DeleteMoreRequestBody();
            inValue.Body.filepaths = filepaths;
            UEditorDemo.UploadFile.DeleteMoreResponse retVal = ((UEditorDemo.UploadFile.UploadFileSoap)(this)).DeleteMore(inValue);
            return retVal.Body.DeleteMoreResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UEditorDemo.UploadFile.DeleteMoreResponse> UEditorDemo.UploadFile.UploadFileSoap.DeleteMoreAsync(UEditorDemo.UploadFile.DeleteMoreRequest request) {
            return base.Channel.DeleteMoreAsync(request);
        }
        
        public System.Threading.Tasks.Task<UEditorDemo.UploadFile.DeleteMoreResponse> DeleteMoreAsync(UEditorDemo.UploadFile.ArrayOfString filepaths) {
            UEditorDemo.UploadFile.DeleteMoreRequest inValue = new UEditorDemo.UploadFile.DeleteMoreRequest();
            inValue.Body = new UEditorDemo.UploadFile.DeleteMoreRequestBody();
            inValue.Body.filepaths = filepaths;
            return ((UEditorDemo.UploadFile.UploadFileSoap)(this)).DeleteMoreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UEditorDemo.UploadFile.GetFileBytesResponse UEditorDemo.UploadFile.UploadFileSoap.GetFileBytes(UEditorDemo.UploadFile.GetFileBytesRequest request) {
            return base.Channel.GetFileBytes(request);
        }
        
        public byte[] GetFileBytes(string filepath) {
            UEditorDemo.UploadFile.GetFileBytesRequest inValue = new UEditorDemo.UploadFile.GetFileBytesRequest();
            inValue.Body = new UEditorDemo.UploadFile.GetFileBytesRequestBody();
            inValue.Body.filepath = filepath;
            UEditorDemo.UploadFile.GetFileBytesResponse retVal = ((UEditorDemo.UploadFile.UploadFileSoap)(this)).GetFileBytes(inValue);
            return retVal.Body.GetFileBytesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UEditorDemo.UploadFile.GetFileBytesResponse> UEditorDemo.UploadFile.UploadFileSoap.GetFileBytesAsync(UEditorDemo.UploadFile.GetFileBytesRequest request) {
            return base.Channel.GetFileBytesAsync(request);
        }
        
        public System.Threading.Tasks.Task<UEditorDemo.UploadFile.GetFileBytesResponse> GetFileBytesAsync(string filepath) {
            UEditorDemo.UploadFile.GetFileBytesRequest inValue = new UEditorDemo.UploadFile.GetFileBytesRequest();
            inValue.Body = new UEditorDemo.UploadFile.GetFileBytesRequestBody();
            inValue.Body.filepath = filepath;
            return ((UEditorDemo.UploadFile.UploadFileSoap)(this)).GetFileBytesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UEditorDemo.UploadFile.ShowImageResponse UEditorDemo.UploadFile.UploadFileSoap.ShowImage(UEditorDemo.UploadFile.ShowImageRequest request) {
            return base.Channel.ShowImage(request);
        }
        
        public string ShowImage(string path, int PointX, int PointY, int CutWidth, int CutHeight, int PicWidth, int PicHeight, string FolderName) {
            UEditorDemo.UploadFile.ShowImageRequest inValue = new UEditorDemo.UploadFile.ShowImageRequest();
            inValue.Body = new UEditorDemo.UploadFile.ShowImageRequestBody();
            inValue.Body.path = path;
            inValue.Body.PointX = PointX;
            inValue.Body.PointY = PointY;
            inValue.Body.CutWidth = CutWidth;
            inValue.Body.CutHeight = CutHeight;
            inValue.Body.PicWidth = PicWidth;
            inValue.Body.PicHeight = PicHeight;
            inValue.Body.FolderName = FolderName;
            UEditorDemo.UploadFile.ShowImageResponse retVal = ((UEditorDemo.UploadFile.UploadFileSoap)(this)).ShowImage(inValue);
            return retVal.Body.ShowImageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UEditorDemo.UploadFile.ShowImageResponse> UEditorDemo.UploadFile.UploadFileSoap.ShowImageAsync(UEditorDemo.UploadFile.ShowImageRequest request) {
            return base.Channel.ShowImageAsync(request);
        }
        
        public System.Threading.Tasks.Task<UEditorDemo.UploadFile.ShowImageResponse> ShowImageAsync(string path, int PointX, int PointY, int CutWidth, int CutHeight, int PicWidth, int PicHeight, string FolderName) {
            UEditorDemo.UploadFile.ShowImageRequest inValue = new UEditorDemo.UploadFile.ShowImageRequest();
            inValue.Body = new UEditorDemo.UploadFile.ShowImageRequestBody();
            inValue.Body.path = path;
            inValue.Body.PointX = PointX;
            inValue.Body.PointY = PointY;
            inValue.Body.CutWidth = CutWidth;
            inValue.Body.CutHeight = CutHeight;
            inValue.Body.PicWidth = PicWidth;
            inValue.Body.PicHeight = PicHeight;
            inValue.Body.FolderName = FolderName;
            return ((UEditorDemo.UploadFile.UploadFileSoap)(this)).ShowImageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UEditorDemo.UploadFile.DownLoadFileResponse UEditorDemo.UploadFile.UploadFileSoap.DownLoadFile(UEditorDemo.UploadFile.DownLoadFileRequest request) {
            return base.Channel.DownLoadFile(request);
        }
        
        public string DownLoadFile(string sUrl, string sDownFold) {
            UEditorDemo.UploadFile.DownLoadFileRequest inValue = new UEditorDemo.UploadFile.DownLoadFileRequest();
            inValue.Body = new UEditorDemo.UploadFile.DownLoadFileRequestBody();
            inValue.Body.sUrl = sUrl;
            inValue.Body.sDownFold = sDownFold;
            UEditorDemo.UploadFile.DownLoadFileResponse retVal = ((UEditorDemo.UploadFile.UploadFileSoap)(this)).DownLoadFile(inValue);
            return retVal.Body.DownLoadFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UEditorDemo.UploadFile.DownLoadFileResponse> UEditorDemo.UploadFile.UploadFileSoap.DownLoadFileAsync(UEditorDemo.UploadFile.DownLoadFileRequest request) {
            return base.Channel.DownLoadFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<UEditorDemo.UploadFile.DownLoadFileResponse> DownLoadFileAsync(string sUrl, string sDownFold) {
            UEditorDemo.UploadFile.DownLoadFileRequest inValue = new UEditorDemo.UploadFile.DownLoadFileRequest();
            inValue.Body = new UEditorDemo.UploadFile.DownLoadFileRequestBody();
            inValue.Body.sUrl = sUrl;
            inValue.Body.sDownFold = sDownFold;
            return ((UEditorDemo.UploadFile.UploadFileSoap)(this)).DownLoadFileAsync(inValue);
        }
    }
}
